services:
  db:
    build:
      context: ./
      dockerfile: db.dockerfile
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready
      interval: 1s
      retries: 10

  graphql:
    image: node:18.13.0
    command: yarn tsx watch --clear-screen=false --inspect=0.0.0.0:9229 src/server.ts
    working_dir: /home/node/app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://sample_user:local@db:5432/sample_app
    volumes:
      - ./:/home/node/app/
    ports:
      - 4000:4000
      - 9229:9229
